// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-XG9JBbxvM6Dpc2kCi09uLKrWJcc-Rw',
    appId: '1:571318968516:web:8a9b18a1695b9377152991',
    messagingSenderId: '571318968516',
    projectId: 'tsa-software-dev-76048',
    authDomain: 'tsa-software-dev-76048.firebaseapp.com',
    storageBucket: 'tsa-software-dev-76048.appspot.com',
    measurementId: 'G-GQK95YP686',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsoyElJAZ19cguyAc-Qmt9ws2GWZ4pyE',
    appId: '1:571318968516:android:32bac7880be51d6b152991',
    messagingSenderId: '571318968516',
    projectId: 'tsa-software-dev-76048',
    storageBucket: 'tsa-software-dev-76048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qwjIXvecqRwGv9L5wWIAIaXWEfN3zfQ',
    appId: '1:571318968516:ios:f2a98d3b6ae9c1da152991',
    messagingSenderId: '571318968516',
    projectId: 'tsa-software-dev-76048',
    storageBucket: 'tsa-software-dev-76048.appspot.com',
    iosBundleId: 'com.example.sleepApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qwjIXvecqRwGv9L5wWIAIaXWEfN3zfQ',
    appId: '1:571318968516:ios:9c0a9f263d73b446152991',
    messagingSenderId: '571318968516',
    projectId: 'tsa-software-dev-76048',
    storageBucket: 'tsa-software-dev-76048.appspot.com',
    iosBundleId: 'com.example.sleepApplication.RunnerTests',
  );
}
